kind: pipeline
type: kubernetes
name: default

steps:
- name: build & publish
  image: plugins/docker
  settings:
    repo: ryuneeee/finance
    auto_tag: true
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
