kind: pipeline
type: kubernetes
name: default

- name: build & publish
  image: plugins/docker
  settings:
    tag: latest
    repo: ryuneeee/finance
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
