kind: pipeline
type: kubernetes
name: default

steps:
#- name: tag
#  image: python:3.8
#  commands:
#    - echo $(git log -1 --pretty=%h) > .tags

- name: build & publish
  image: plugins/docker
  settings:
    repo: ryuneeee/finance
    tag: latest
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
