kind: pipeline
type: kubernetes
name: default

steps:
- name: test
  image: python:3.8
  commands:
  - pip install -r requirements.txt
  - docker build -t ryuneeee/finance:$(git log -1 --pretty=%h) .
